### ISSUE TITLE
Loading supported themes list from jsonresume.org

### ISSUE THREAD

**Issue by mrancourt** [mattberther/gulp-resume#2]
Hi @mattberther, 
Just found your gulp plugin today, it's really useful for me! 

I think it would be nice to fetch the supported themes list directly from the jsonresume themes registry. 
The whole list is available at `https://themes.jsonresume.org/themes.json` and the output looks like this : 
<pre>
{
  "themes": {
    "<b>flat</b>": {
      "author": "Mattias Erming",
      "versions": [
        "0.3.2",
        "0.3.7"
      ]
    },
    "<b>smart</b>": {
      "author": "Piotr D\u00c5\u00bcaluk",
      "versions": [
        "1.0.2"
      ]
    },
    ...
</pre>
So I guess it wouldn't be too hard to get all of them from the first level keys of the `themes` Object.

Let me know what you think, I would be happy to open up a PR for it if you want. 

Thanks!

**Comment by mattberther** [comment]
@mrancourt Thank you. Yes, Id love to see this. Wonder if we could leverage gulp-prompt and gulp-config to ask the user to select the theme and then add it to a config file.

If you want to open a PR, Id welcome it. Thanks!

**Comment by mrancourt** [comment]
I must say it would be nice to specify the theme by prompt and let it remember it in a config file. Maybe we could also add the format and source file location in those configs.
